coverage:
  paths:
    - coverage.out
    - internal/frontend/coverage/lcov.info
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
    - 'internal/frontend/src/**/*.ts'
    - 'internal/frontend/src/**/*.tsx'
    - '!internal/frontend/src/**/*.test.ts'
    - '!internal/frontend/src/**/*.test.tsx'
    - '!internal/frontend/node_modules/**'
  test:
    - '**/*_test.go'
    - 'internal/frontend/src/**/*.test.ts'
    - 'internal/frontend/src/**/*.test.tsx'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
